name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: STEP | BUILDING ... 
    steps:
      - name: Heollo world
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heoooooo
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Heeeee   
        run: npm ci

      - name: Check for Affected Projects
        uses: dkhunt27/action-nx-affected-list@v4
        id: checkForAffected

  
