name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  myjob:
    runs-on: ubuntu-latest
    # GITHUB_TOKEN 접근 권한
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - name: 1) 모든 브랜치와 커밋을 가져온다.
      - uses: actions/checkout@v3
        with:
          # NX affected가 비교할 수 있는 베이스를 가지도록 모든 브랜치와 커밋을 가져온다.
          fetch-depth: 0

      # 이 이후 단계에서 output이나 환경변수를 이용하여 SHA를 참조할 수 있다.
      - name: 2) `nx affected` 명령어를 위해 base와 head의 SHA를 가져온다.
        uses: nrwl/nx-set-shas@v3
    
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"


