name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: STEP | BUILDING ... 
    steps:
      - name: 기본 환경 설정
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      - name: 영향받는 프로젝트 검사
        uses: dkhunt27/action-nx-affected-list@v4
        id: checkForAffected

      - run: |
          echo "${{ steps.checkForAffected.outputs.affected }}"
          



