name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: STEP | BUILDING
    outputs: 
      affectedApps: ${{ steps.checkForAffected.outputs.affectedApps }}
    steps:
      - name: << Checkout to repository >>
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: << Setting node >>
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: << Install NPM >>   
        run: npm ci
      
      - name: << Build only affected >>
        uses: nrwl/nx-set-shas@v3
      - run: npx nx affected --target=build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}  

      - name: << Check for affected projects >>
        uses: dkhunt27/action-nx-affected-list@v4
        id: checkForAffected

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          affectedApps: needs.build.outputs.affectedApps
    steps:
      - name: STEP | DEPLOY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          AWS_S3_BUCKET: 'peter-latte'
          SOURCE_DIR: './dist/packages/app'
        run: echo "세번돼랑"
      
      
          
