name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: STEP | BUILDING ... 
    steps:
      - name: << Checkout to repository >>
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: << Setting node >>
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: << Install NPM >>   
        run: npm ci
      
      - name: << Build only affected >>
        uses: nrwl/nx-set-shas@v3
      - run: npx nx affected --target=build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}  

      - name: << Check for affected projects >>
        uses: dkhunt27/action-nx-affected-list@v4
        id: checkForAffected

  deploy:
      needs: build
      runs-on: ubuntu-latest
      name: STEP | DEPLOTING ... 
      steps:
        - if: steps.checkForAffected.outputs.hasAffected == 'true'
          run: echo "여기서는 오직 ${{ steps.checkForAffected.outputs.affectedApps }}"
  
