name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: STEP | BUILDING ... 
    steps:
      - name: Setting
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      - name: check For Affected
        uses: dkhunt27/action-nx-affected-list@v4
        id: checkForAffected
      
      - if: steps.checkForAffected.outputs.hasAffected == 'true'
        name: Build Affected
        uses: nrwl/nx-set-shas@v3
