name: Deploy main to Amazon ECS

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: STEP | BUILDING ... 
    steps:
      - name: Checkout to Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setting Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install NPM   
        run: npm ci
      
      - name: nx affected 명령어를 위해 base와 head의 SHA를 가져온다.
        uses: nrwl/nx-set-shas@v3
      - run: npx nx affected --target=build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}  

      - name: Check for Affected Projects
        uses: dkhunt27/action-nx-affected-list@v4
        id: checkForAffected

      - name: nx affected 명령어를 위해 base와 head의 SHA를 가져온다.
        if: steps.checkForAffected.outputs.hasAffected == 'true'
        run: echo "호잇"
  
